### ISSUE TITLE
Add as an official terraform provider

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/terraform-provider-oneview#42]
It would be good if this could be added to terraform as an official provider rather than being added on separately?

Are there any plans to add this officially?

**Comment by dh2mom247** [comment]
@wingZero21 We originally planned to add as an official provider but due to testing requirements with oneview, it is not an option.

**Comment by wingZero21** [comment]
Hi,

Can you advise why the testing requirements stop this from being an official provider? You could just simply state that the provider at the time works with version X of oneview. 

Or is this testing for something more specific to the terraform version?

**Comment by jsmartt** [comment]
Hi @wingZero21, we definitely went down the road of trying to get this provider included with list of official providers, but Hashicorp's policy at the time required them to be able to thoroughly test the provider themselves and maintain access to OneView infrastructure for debugging/support. Unlike AWS, this is a pretty expensive ask, especially if we want to support multiple versions of OneView and different hardware variants. Additionally, official plugins are restricted to the TF team's release pipeline; HPE would rather control this to be able to release as often as needed without the man in the middle.

That said, TF has changed the plugin model with v0.10 in a very positive way. Instead of building them into the core, they want to enable a true plugin model where providers can be pulled in separately. Right now it's still limited to those *official* plugins, but the plan (according to [this](https://www.terraform.io/upgrade-guides/0-10.html#third-party-provider-plugins)) is to enable third-party plugins like this one to be pulled in very easily.

With all the changes it's definitely worth a re-visit to see how providers like ours can be made more visible. We would definitely love to be able to integrate with or mimic the documentation provided for official TF providers. We just haven't gotten to that yet because we're between resources for this project at the moment.

**Comment by wingZero21** [comment]
Hi,

Thanks for the response. 

Sounds like the plugin model is changing so that at some point in the future this could be pulled in.
