### ISSUE TITLE
DL Server Profiles - Idempotency issue after import

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#449]
## Scenario/Intent

Hello,

Terraform detects a change between the hardware name and the name of a random SP despite it beeing correct when checking OneView and the tfstate. At each `terragrunt plan/apply` a different SP is concerned (seemingly random).

Before running the `terragrunt plan` command, to check for idempotency, I imported all of my Server Profiles with `terraform import` command.

Note: there is about 30 Server Profiles created.

## Environment Details

- OneView Terraform SDK provider: v6.4.0-13
- OneView Appliance Version: 6.30

## Expected Result

```
No changes. Infrastructure is up-to-date.

  # oneview_server_profile.ServerProfiles["myservernameA"]
   resource "oneview_server_profile" "ServerProfiles" {
        [...]
        hardware_name                 = "myservernameA-lc.env.int"
        hardware_uri                  = "/rest/server-hardware/37393150-3032-5A43-3231-323030384A46"
        [...]
        modified                      = "2021-12-16T14:32:43.806Z"
        name                          = "myservernameA"
        [...]
```

### In my configuration file:

```
inputs = {
  server_profiles = [
    {
      server_profile_name      = "myservernameA"
      server_profile_type      = "ServerProfileV12"
      hardware_name            = "myservernameA-lc.env.int"
     [...]
   }
```

### In the tfsate:

```
      "myservernameA": {
          "affinity": "",
          "bios_option": [...]
          "name": "myservernameA"
          [...]
          "hardware_name": "myservernameA-lc.env.int"
```

### Result of `terragrunt plan` command:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # oneview_server_profile.ServerProfiles["myservernameA"] will be updated in-place
  ~ resource "oneview_server_profile" "ServerProfiles" {
        [...]
        hardware_name                 = "otherservernameB-lc.env.int" ~> myservernameA-lc.env.int
        hardware_uri                  = "/rest/server-hardware/37393150-3032-5A43-3231-323030384A46"
        [...]
        modified                      = "2021-12-16T14:32:43.806Z"
        name                          = "otherservernameB" ~> myservernameA
        [...]

```

**Comment by nabhajit-ray** [comment]
Can you please share the configuration file and the plan output? Also is it reproducible everytime?

**Comment by BoudewijnSwen** [comment]
He Claire, I see you been running into some of the same issues as I have. Both with settings the ILO hostname and now this. It might be connected. Or at least, I had the problem that with creating a server profile, you had to reference a hardware_name, which after you apply the profile, is changed. So then in the next run it would not find the hardware name you used initially. Using names to reference objects is always a bit... meh :) 

Anyway, I found a way to work around it. I'll share it, maybe it can help you.

I specify all my servers in a json:
```
{
    "servername1": {
        "ip": "10.13.37.11",
        "serial_number": "ABC",
        "template": "DL360_Gen10_Plus_1_SPT"
    },
    "servername2": {
        "ip": "10.13.37.12",
        "serial_number": "XYZ",
        "template": "DL360_Gen10_Plus_1_SPT"
    }
}
```

In my locals I import these, and separate them by which template I specified for each.
```
locals {
  servers = try(jsondecode(file("${path.module}/servers.json")), {})

  // check if a template value is given per server in the json. 
  // If you would leave the template value empty, it will not try to apply one.
  template_servers = try({ for key, server in local.servers:
    key => server if server.template != ""
  })

  // We have multiple hw types and settings profiles. So I filter each of them into a seperate list.
  DL360_Gen10_Plus_1_SPT = try({ for key, hv in local.template_servers:
    key => server if server.template == "DL360_Gen10_Plus_1_SPT" }, {}
  )
# bottom part of the locals definition omitted.
```

I add all the servers to OV with a for_each over the local.servers. (using the ip value as hostname)

So there are a couple of chicken-egg things going on here. The server will have its name changed by the profile. So I have to find out if it exists still with the old name (factory default) or by the new, intended name, I set with the profile. So I create data sources for both options:
```
data "oneview_server_hardware" "server_sn" { // By serial number
  for_each = local.DL360_Gen10_Plus_1_SPT
  name = format("ILO%s", each.value.serial_number)
}

data "oneview_server_hardware" "server_name" { // By intended hw name
  for_each = local.DL360_Gen10_Plus_1_SPT
  name = format("%s-ilo", each.key)
}
```

Going over all the data source objects I created, to see which ones have a uri set. If they have a uri, it actually found the server hardware in OneView, so that is the hardware name I should use for the server profile.

bottom part of my locals statement:
```
# top part of locals definition omitted
  by_sn_DL360_Gen10_Plus_1_SPT = { for key, hv in local.DL360_Gen10_Plus_1_SPT:
    key => { "hw_name": "ILO${hv.serial_number}" }
    if data.oneview_server_hardware.server_sn[key].uri != null
  }
  by_name_DL360_Gen10_Plus_1_SPT = { for key, hv in local.DL360_Gen10_Plus_1_SPT:
    key => { "hw_name": "${key}-ilo" }
    if data.oneview_server_hardware.server_name[key].uri != null
  }
  // Combining both maps, so I have a single map, containing only server hardware references by name
  // that OneView knows how to find by that name.
  full_DL360_Gen10_Plus_1_M_SPT = merge(local.by_sn_DL360_Gen10_Plus_1_SPT, local.by_name_DL360_Gen10_Plus_1_SPT)
}
```

So now, when you create the profiles, it will always have the correct name set:
```
resource "oneview_server_profile" "DL360_Gen10_Plus_1_SPT" {
  for_each              = local.full_DL360_Gen10_Plus_1_SPT
  name                  = each.key
  hardware_name         = each.value.hw_name
```

It is a bit of a hassle, but it seems to work for me.

btw, you see me calling it templates, which is for server profile templates. However, if you reference a actual template while creating a server profile, the provider bugs out. I have an open issue about this here as well: [Issue 448](https://github.com/HewlettPackard/terraform-provider-oneview/issues/448)
So what I did for now is copying all my template settings directly into the server profile resource block. This works, however, when I am going to update them (change the firmware for example), I will probably be in trouble. But I'll cross that bridge when I get there ;)

**Comment by nabhajit-ray** [comment]
Since there are no response,we are closing this.
